### ISSUE TITLE
shm 관련 문서 개선

### ISSUE THREAD

**Issue by seojangho** [bacchus-snu/sgs#13]
사용자 문의 메일을 일부 인용하자면,

> sgs docs에 나와있는대로 pod을 생성한 후에 df -h를 해보면 shm가 64MB로 설정되어 있습니다.
> pytorch에서 dataloader의 num_workers를 키우면 데이터 로딩 속도가 빨라지는 대신 shared memory를 많이 사용하게 됩니다.
> 64MB로는 충분한 속도를 내기 어렵기 때문에 이를 늘릴 수 있는 방법이 docs에 추가되어 있으면 좋을 것 같아서 건의드립니다.

```yaml
- name: dshm
  emptyDir:
        medium: Memory
```
